# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/da/Desktops/Desktop1/pr2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/da/Desktops/Desktop1/pr2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/da/Desktops/Desktop1/pr2/CMakeFiles /home/da/Desktops/Desktop1/pr2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/da/Desktops/Desktop1/pr2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named myutil

# Build rule for target.
myutil: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 myutil
.PHONY : myutil

# fast build rule for target.
myutil/fast:
	$(MAKE) -f CMakeFiles/myutil.dir/build.make CMakeFiles/myutil.dir/build
.PHONY : myutil/fast

Main.o: Main.c.o

.PHONY : Main.o

# target to build an object file
Main.c.o:
	$(MAKE) -f CMakeFiles/myutil.dir/build.make CMakeFiles/myutil.dir/Main.c.o
.PHONY : Main.c.o

Main.i: Main.c.i

.PHONY : Main.i

# target to preprocess a source file
Main.c.i:
	$(MAKE) -f CMakeFiles/myutil.dir/build.make CMakeFiles/myutil.dir/Main.c.i
.PHONY : Main.c.i

Main.s: Main.c.s

.PHONY : Main.s

# target to generate assembly for a file
Main.c.s:
	$(MAKE) -f CMakeFiles/myutil.dir/build.make CMakeFiles/myutil.dir/Main.c.s
.PHONY : Main.c.s

logs.o: logs.c.o

.PHONY : logs.o

# target to build an object file
logs.c.o:
	$(MAKE) -f CMakeFiles/myutil.dir/build.make CMakeFiles/myutil.dir/logs.c.o
.PHONY : logs.c.o

logs.i: logs.c.i

.PHONY : logs.i

# target to preprocess a source file
logs.c.i:
	$(MAKE) -f CMakeFiles/myutil.dir/build.make CMakeFiles/myutil.dir/logs.c.i
.PHONY : logs.c.i

logs.s: logs.c.s

.PHONY : logs.s

# target to generate assembly for a file
logs.c.s:
	$(MAKE) -f CMakeFiles/myutil.dir/build.make CMakeFiles/myutil.dir/logs.c.s
.PHONY : logs.c.s

polzovatel.o: polzovatel.c.o

.PHONY : polzovatel.o

# target to build an object file
polzovatel.c.o:
	$(MAKE) -f CMakeFiles/myutil.dir/build.make CMakeFiles/myutil.dir/polzovatel.c.o
.PHONY : polzovatel.c.o

polzovatel.i: polzovatel.c.i

.PHONY : polzovatel.i

# target to preprocess a source file
polzovatel.c.i:
	$(MAKE) -f CMakeFiles/myutil.dir/build.make CMakeFiles/myutil.dir/polzovatel.c.i
.PHONY : polzovatel.c.i

polzovatel.s: polzovatel.c.s

.PHONY : polzovatel.s

# target to generate assembly for a file
polzovatel.c.s:
	$(MAKE) -f CMakeFiles/myutil.dir/build.make CMakeFiles/myutil.dir/polzovatel.c.s
.PHONY : polzovatel.c.s

procesi.o: procesi.c.o

.PHONY : procesi.o

# target to build an object file
procesi.c.o:
	$(MAKE) -f CMakeFiles/myutil.dir/build.make CMakeFiles/myutil.dir/procesi.c.o
.PHONY : procesi.c.o

procesi.i: procesi.c.i

.PHONY : procesi.i

# target to preprocess a source file
procesi.c.i:
	$(MAKE) -f CMakeFiles/myutil.dir/build.make CMakeFiles/myutil.dir/procesi.c.i
.PHONY : procesi.c.i

procesi.s: procesi.c.s

.PHONY : procesi.s

# target to generate assembly for a file
procesi.c.s:
	$(MAKE) -f CMakeFiles/myutil.dir/build.make CMakeFiles/myutil.dir/procesi.c.s
.PHONY : procesi.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... myutil"
	@echo "... edit_cache"
	@echo "... Main.o"
	@echo "... Main.i"
	@echo "... Main.s"
	@echo "... logs.o"
	@echo "... logs.i"
	@echo "... logs.s"
	@echo "... polzovatel.o"
	@echo "... polzovatel.i"
	@echo "... polzovatel.s"
	@echo "... procesi.o"
	@echo "... procesi.i"
	@echo "... procesi.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

